### ISSUE TITLE
Weekly Newsletter for Cyber Republic

### ISSUE THREAD

**Issue by kpachhai** [cyber-republic/CyberRepublic#1]
This is on hold until we add Wiki/Blog feature to cyberrepublic.org site.
However, the newsletter should include the following and much more:
- Updates made to CR website over the last week(technical updates + commit messages, etc)
- New Tasks that were created
- Stats on CRcles(# of people for each circle, new posts, etc)
- New meetup proposals that are in the works and upcoming meetups
- Community contributions(articles, videos, etc)
- Upcoming milestones for CR
- Need help section(Eg. for react native framework, backend logic, etc)

**Comment by luckyyang** [comment]
Seems we already finished this issue, close it
