### ISSUE TITLE
🐛 Like/dislike button counter (suggestion page)

### ISSUE THREAD

**Issue by jmsaulnier** [cyber-republic/CyberRepublic#112]
### Issue 

- If user click quickly multiple times on the likes/dislikes button you can increase/decrease counter (eg: -1, 3)
- If I click on like and dislike, both have “1” value 

### Platform 

Tested only on iOS Safari so maybe it’s an issue on other platform/browser as well 

### Expected behaviour 

- Value should be only empty or “1” and for only one button max

**Comment by luckyyang** [comment]
Will look into it 👍

**Comment by luckyyang** [comment]
Fixed

**Comment by luckyyang** [comment]
This issue happened on all kinds of browsers
