### ISSUE TITLE
🐛 Layout on mobile for proposal detail page make it difficult to read

### ISSUE THREAD

**Issue by jmsaulnier** [cyber-republic/CyberRepublic#113]
### Issue
Column for the text is very narrow, some UI elements position can be improve 

### Platform

Tested on iPhone SE, but issue with multiple screen size on mobile 

### Behaviour expected

Text should take almost the full width on mobile

**Comment by luckyyang** [comment]
Will fix it, thanks!

**Comment by luckyyang** [comment]
We are doing proposal redesign, so be patient, thanks.

**Comment by luckyyang** [comment]
fixed
