### ISSUE TITLE
200 Characters Max Makes Sense For Chinese, Not English. 

### ISSUE THREAD

**Issue by mrpqzm** [cyber-republic/CyberRepublic#165]
Dear CR Team, 

Ya'll done did messed up. 

I am trying to submit a proposal, and because my proposal is in English. The system is not letting continue unless I type under 200 characters. (Despite the text saying 200 worlds). 

This may make sense for Chinese, however, for English, you really should allow for 200 worlds. The text on the screen may say "200 worlds" but only "200 characters" are allowed atm. 

Ya'll need to change your code so that instead of counting the entire string, it counts the " " (spaces) inside the string. 

Look forward to submitting my proposal.

**Comment by mrpqzm** [comment]
[https://imgur.com/a/Z8u0Eje](url)

**Comment by billie66** [comment]
I will check it, thanks

**Comment by billie66** [comment]
fixed
