### ISSUE TITLE
🐛 Login / Register is hidden (menu on mobile)

### ISSUE THREAD

**Issue by jmsaulnier** [cyber-republic/CyberRepublic#51]
On small devices (iPhone SE for example) you can't click on Login / Register buttons from the main menu

![screen shot 2019-02-06 at 4 17 22 pm](https://user-images.githubusercontent.com/145750/52383278-854fb880-2a2d-11e9-97d4-8aa16b223606.png)

**Comment by luckyyang** [comment]
Thanks, will fix it

**Comment by luckyyang** [comment]
fixed
