### ISSUE TITLE
🧐 Disable Analytics trackers by default

### ISSUE THREAD

**Issue by jmsaulnier** [cyber-republic/CyberRepublic#52]
All trackers should be disabled by default (Segment, Google Analytics)
We can ask users if they want to activate trackers in order to improve user experience / stats (small rewards for them if they are agree?) but it should be anonymous

Moreover do we really need to share email and firstname / lastname to third party?
https://github.com/cyber-republic/CyberRepublic/blob/master/front-end/src/app.js#L110

**Comment by luckyyang** [comment]
Trackers are currently disabled until we decide how to use them: https://github.com/cyber-republic/CyberRepublic/blob/master/front-end/public/index.html#L15

I agree it's not a good idea to collect user's info with the tracker tools, I will remove them.

**Comment by luckyyang** [comment]
For the UX advice, sounds interesting, @xiaohou77 Could you evaluate it?

**Comment by luckyyang** [comment]
Sensitive info collection code had been removed
