### ISSUE TITLE
✏️ Add Meta Tags for Social Media / Update meta description content

### ISSUE THREAD

**Issue by jmsaulnier** [cyber-republic/CyberRepublic#61]
When sharing on social media good description & image are required
https://css-tricks.com/essential-meta-tags-social-media/

meta name="description" is for now "Elastos Cyber Republic" only - Twitter CR account description is much better and give more info about it

<img width="646" alt="screen shot 2019-02-12 at 4 42 29 pm" src="https://user-images.githubusercontent.com/145750/52678152-72cdf700-2ee5-11e9-98bf-7f72ce010b44.png">

**Comment by luckyyang** [comment]
Thanks, will do
