### ISSUE TITLE
🐛Team list API request error

### ISSUE THREAD

**Issue by jmsaulnier** [cyber-republic/CyberRepublic#63]
On https://www.cyberrepublic.org/developer page, there is a link to Developer team search ("Connect, Form Teams and work on projects") https://www.cyberrepublic.org/developer/search?lookingFor=TEAM&sortBy=createdAt&sortOrder=DESC

**The GET request**

```https://api.cyberrepublic.org/api/team/list?sortBy=createdAt&sortOrder=DESC&page=1&results=5&type=TEAM```

**response**

```{"code":-2,"type":"MongoError","error":"bad sort specification"}```

**Comment by luckyyang** [comment]
Thanks, will fix it

**Comment by luckyyang** [comment]
Fixed and verified
