### ISSUE TITLE
🐛 Links detection in text block

### ISSUE THREAD

**Issue by jmsaulnier** [cyber-republic/CyberRepublic#69]
As you can see in this page someone added some links but she didn't add extra space between links and "(" & ")" so when the user clicks on these links it goes to for example ```https://twitter.com/cyber__republic)``` rather than ```https://twitter.com/cyber__republic```
https://www.cyberrepublic.org/suggestion/5c6b362072fc340094d08fac

Looks like the issue is coming from the JS lib https://zenoamaro.github.io/react-quill/

**Comment by jmsaulnier** [comment]
I tried different editors and they all have the issue for this case  🤔 I guess add an "Edit" Suggestion option would help for this issue

**Comment by luckyyang** [comment]
Thanks, "Edit Suggestion" is already on our backlog

**Comment by luckyyang** [comment]
Suggestion content history will be kept
