### ISSUE TITLE
Typo on home page

### ISSUE THREAD

**Issue by kenpole** [cyber-republic/CyberRepublic#84]
"A diverse, robust community of skill-focused sub-groups whose leaders, developers, and organizers working together to promote Elastos in our communities. Membership is open to all."

^Typo, it should be "are working"

**Comment by luckyyang** [comment]
Confirmed with the team it's not a typo, thanks @kenpole

**Comment by kpachhai** [comment]
@luckyyang The quote above has some grammar error which is what Ken was talking about. 

> A diverse, robust community of skill-focused sub-groups whose leaders, developers, and organizers working together to promote Elastos in our communities. Membership is open to all.

Should be
> A diverse, robust community of skill-focused sub-groups whose leaders, developers, and organizers work together to promote Elastos in our communities. Membership is open to all.

Or 
> A diverse, robust community of skill-focused sub-groups whose leaders, developers, and organizers are working together to promote Elastos in our communities. Membership is open to all.

Or, change it to something different
But either way, the original text that's on the website needs to be fixed as that's not gramatically correct.

**Comment by luckyyang** [comment]
@kpachhai Thanks for the clarification, I will change the text.
